#!/usr/bin/env python3
"""AURA wake-word SaaS — one-command customer onboarding.

Turns a customer's labelled dataset into a versioned, signed, ready-to-ship AURA
bundle with a single command:

    python serve_train.py --wake-word "hey nova" --data /path/to/customer_dataset \
        [--customer acme] [--license-id ACME-2026-001] [--version 20260709] \
        [--sign-key keys/acme.key] [--no-stage2]

What it does (orchestration only — it never edits train.py/evaluate.py):
  1. Synthesizes a temp config.yaml from this repo's config.yaml defaults, overriding
     wake_word / dataset_dir / customer / license_id / version / sign_key (+ --no-stage2).
  2. Runs `python train.py --config <temp>`  (trains + calibrates + BUNDLES).
  3. Runs `python evaluate.py --config <temp>` (streaming FA/hr, FRR, ECE).
  4. Prints a concise METRICS REPORT CARD and the final signed deliverable .zip path.

The dataset must be laid out as:
    <data>/positive/*.wav      (clips that SAY the wake word)
    <data>/negative/*.wav      (everything else)
16 kHz mono WAV. See datasets/README.md.
"""
import argparse
import datetime
import glob
import json
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))


# --------------------------------------------------------------------------- helpers
def slugify(name):
    """'Hey Nova!' -> 'hey_nova'. The engine + artifact naming want a no-space token."""
    s = re.sub(r"[^0-9a-zA-Z]+", "_", name.strip().lower())
    return s.strip("_") or "wake_word"


def yaml_str(v):
    """Emit a value for the tiny YAML we synthesize (readable by pyyaml AND train.py's
    fallback mini-parser). Paths use single quotes so backslashes aren't escaped."""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("\\", "/").replace("'", "''") + "'"


def synth_config(dst_path, base, wake_word, dataset_dir, output_dir, version,
                 customer, license_id, sign_key, stage2_on):
    """Write a temp config.yaml: base defaults + per-customer overrides."""
    stage2_base = base.get("stage2") or {}
    lines = [
        "# Auto-generated by serve_train.py — per-customer AURA training run.",
        "# Safe to delete; regenerated on every onboarding.",
        f"wake_word: {yaml_str(wake_word)}",
        f"dataset_dir: {yaml_str(dataset_dir)}",
        f"output_dir: {yaml_str(output_dir)}",
        f"epochs: {yaml_str(int(base.get('epochs', 25)))}",
        f"arch: {yaml_str(base.get('arch', 'dscnn'))}",
        "stage2:",
        f"  enabled: {yaml_str(bool(stage2_on))}",
        f"  arch: {yaml_str(stage2_base.get('arch', 'cnn'))}",
        f"sample_rate: {yaml_str(int(base.get('sample_rate', 16000)))}",
        f"calibrate: {yaml_str(bool(base.get('calibrate', True)))}",
        "# --- SaaS / delivery additions (train.py + tools/bundle.py read these) ---",
        f"version: {yaml_str(version)}",
        f"customer: {yaml_str(customer)}",
        f"license_id: {yaml_str(license_id)}",
        f"sign_key: {yaml_str(sign_key)}",
        "",
    ]
    with open(dst_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def run_stream(cmd, cwd):
    """Run a subprocess, echoing its output live while capturing it. Returns (rc, text)."""
    print(f"\n$ {' '.join(cmd)}\n", flush=True)
    proc = subprocess.Popen(cmd, cwd=cwd, stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT, text=True, bufsize=1)
    chunks = []
    for line in proc.stdout:
        sys.stdout.write(line)
        sys.stdout.flush()
        chunks.append(line)
    proc.wait()
    return proc.returncode, "".join(chunks)


def _f(pattern, text, group=1, cast=float):
    m = re.search(pattern, text)
    if not m:
        return None
    try:
        return cast(m.group(group))
    except (ValueError, IndexError):
        return None


def parse_train(text):
    m = {}
    m["stage1_recall"] = _f(r"\[stage1/[^\]]+\]\s+F1=[\d.]+\s+recall=([\d.]+)", text)
    m["stage1_size_kb"] = _f(r"\[stage1/[^\]]+\].*?size=([\d.]+)KB", text)
    m["stage2_recall"] = _f(r"\[stage2/[^\]]+\]\s+F1=[\d.]+\s+recall=([\d.]+)", text)
    m["stage2_size_kb"] = _f(r"\[stage2/[^\]]+\].*?size=([\d.]+)KB", text)
    return m


def parse_eval(text):
    m = {}
    m["op_M"] = _f(r"operating point:\s*M=(\d+)", text, cast=int)
    m["stage1_thr"] = _f(r"stage1_thr=([\d.]+)", text)
    m["stage2_thr"] = _f(r"stage2_thr=([\d.]+)", text)
    m["fa_per_hr"] = _f(r"FA/hr=([\d.]+)", text)
    m["frr"] = _f(r"FRR=([\d.]+)%", text)
    m["ece"] = _f(r"ECE=([\d.]+)", text)
    m["auroc"] = _f(r"AUROC=([\d.]+)", text)
    m["total_size_kb"] = _f(r"model size=([\d.]+)\s*KB", text)
    return m


def locate_bundle(dist_root, slug, version):
    """Find the bundle dir + zip the other agent's bundler produced."""
    base = dist_root if os.path.isabs(dist_root) else os.path.join(HERE, dist_root)
    want = f"{slug}_v{version}"
    bdir = os.path.join(base, want)
    zpath = os.path.join(base, want + ".zip")
    if os.path.isdir(bdir) or os.path.isfile(zpath):
        return (bdir if os.path.isdir(bdir) else None,
                zpath if os.path.isfile(zpath) else None)
    # fallback: newest matching zip (in case version/date drifted)
    zips = sorted(glob.glob(os.path.join(base, f"{slug}_v*.zip")),
                  key=os.path.getmtime, reverse=True)
    dirs = sorted(glob.glob(os.path.join(base, f"{slug}_v*")),
                  key=os.path.getmtime, reverse=True)
    dirs = [d for d in dirs if os.path.isdir(d)]
    return (dirs[0] if dirs else None, zips[0] if zips else None)


def fmt(v, spec="{}", dash="n/a"):
    return dash if v is None else spec.format(v)


# --------------------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser(
        prog="serve_train.py",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="AURA wake-word SaaS: one command from a customer dataset to a "
                    "versioned, signed, deliverable bundle.",
        epilog="Example:\n"
               "  python serve_train.py --wake-word \"hey nova\" --data ./customer_acme \\\n"
               "      --customer acme --license-id ACME-2026-001 --sign-key keys/acme.key\n")
    ap.add_argument("--wake-word", required=True,
                    help="Wake phrase, e.g. \"hey nova\" (slugified for artifact naming).")
    ap.add_argument("--data", required=True,
                    help="Customer dataset dir with positive/ and negative/ *.wav subfolders.")
    ap.add_argument("--customer", default=None,
                    help="Customer name - watermarked into the bundle (model_tag) + manifest.")
    ap.add_argument("--license-id", default=None,
                    help="Per-bundle license id, recorded in the signed manifest.")
    ap.add_argument("--version", default=None,
                    help="Bundle version (default: today's UTC date YYYYMMDD).")
    ap.add_argument("--sign-key", default=None,
                    help="Path to an HMAC key file; enables manifest signing.")
    ap.add_argument("--no-stage2", action="store_true",
                    help="Train Stage-1 only (disable the Stage-2 verifier cascade).")
    ap.add_argument("--dist-root", default="dist",
                    help="Where the deliverable bundle/zip land (default: dist/).")
    ap.add_argument("--keep-config", action="store_true",
                    help="Keep the synthesized temp config.yaml for inspection.")
    args = ap.parse_args()

    slug = slugify(args.wake_word)
    version = args.version or datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%d")

    # ---- validate dataset ----
    data_dir = os.path.abspath(args.data)
    if not os.path.isdir(data_dir):
        sys.exit(f"ERROR: dataset dir not found: {data_dir}\n"
                 f"Expected {data_dir}/positive/*.wav and {data_dir}/negative/*.wav "
                 f"(16 kHz mono WAV; see datasets/README.md).")
    pos = os.path.join(data_dir, "positive")
    neg = os.path.join(data_dir, "negative")
    missing = [d for d in (pos, neg) if not os.path.isdir(d)]
    if missing:
        sys.exit("ERROR: dataset is missing required subfolder(s): "
                 + ", ".join(missing) + "\n"
                 f"Lay the data out as {data_dir}/positive/*.wav and "
                 f"{data_dir}/negative/*.wav (see datasets/README.md).")
    n_pos = len(glob.glob(os.path.join(pos, "*.wav")))
    n_neg = len(glob.glob(os.path.join(neg, "*.wav")))
    if n_pos == 0:
        sys.exit(f"ERROR: no positive WAVs in {pos} — at least a handful of clips that "
                 f"SAY \"{args.wake_word}\" are required.")

    # ---- validate sign key (optional) ----
    sign_key = None
    if args.sign_key:
        sign_key = os.path.abspath(args.sign_key)
        if not os.path.isfile(sign_key):
            sys.exit(f"ERROR: --sign-key file not found: {sign_key}")

    # ---- defaults from repo config.yaml ----
    sys.path.insert(0, HERE)
    from train import load_config
    base_cfg_path = os.path.join(HERE, "config.yaml")
    base = load_config(base_cfg_path) if os.path.exists(base_cfg_path) else {}

    output_dir = os.path.join("dist", "_work", slug)  # per-customer, kept off default models/
    stage2_on = not args.no_stage2

    print("=" * 70)
    print(f"AURA onboarding  |  wake word: \"{args.wake_word}\"  (slug: {slug})")
    print(f"  version   : {version}")
    print(f"  customer  : {args.customer or '-'}")
    print(f"  license   : {args.license_id or '-'}")
    print(f"  signing   : {'yes (' + sign_key + ')' if sign_key else 'no'}")
    print(f"  stage2    : {'on' if stage2_on else 'off'}")
    print(f"  dataset   : {data_dir}  ({n_pos} pos / {n_neg} neg WAVs)")
    print("=" * 70)

    # ---- synth temp config ----
    fd, cfg_path = tempfile.mkstemp(prefix=f"serve_{slug}_", suffix=".yaml")
    os.close(fd)
    synth_config(cfg_path, base, slug, data_dir, output_dir, version,
                 args.customer, args.license_id, sign_key, stage2_on)

    train_out = eval_out = ""
    try:
        # ---- 1) TRAIN (+ calibrate + bundle) ----
        rc, train_out = run_stream([sys.executable, "train.py", "--config", cfg_path], cwd=HERE)
        if rc != 0:
            sys.exit(f"\nERROR: train.py failed (exit {rc}). See output above.")

        # ---- 2) EVALUATE ----
        rc, eval_out = run_stream([sys.executable, "evaluate.py", "--config", cfg_path], cwd=HERE)
        if rc != 0:
            print(f"\nWARNING: evaluate.py exited {rc}; report card metrics may be partial.")
    finally:
        if args.keep_config:
            print(f"\n(kept temp config: {cfg_path})")
        else:
            try:
                os.remove(cfg_path)
            except OSError:
                pass

    tm = parse_train(train_out)
    em = parse_eval(eval_out)

    # ---- locate deliverable + read manifest for licensing facts ----
    bundle_dir, zip_path = locate_bundle(args.dist_root, slug, version)
    manifest = {}
    if bundle_dir:
        mpath = os.path.join(bundle_dir, "manifest.json")
        if os.path.isfile(mpath):
            try:
                with open(mpath, encoding="utf-8") as f:
                    manifest = json.load(f)
            except (OSError, ValueError):
                manifest = {}
    model_tag = None
    lbl = os.path.join(bundle_dir, "labels.json") if bundle_dir else None
    if lbl and os.path.isfile(lbl):
        try:
            with open(lbl, encoding="utf-8") as f:
                model_tag = json.load(f).get("model_tag")
        except (OSError, ValueError):
            pass

    signed = manifest.get("signature") not in (None, "", "null")

    # ---- METRICS REPORT CARD ----
    line = "-" * 70
    print("\n" + "=" * 70)
    print("  METRICS REPORT CARD")
    print("=" * 70)
    print(f"  Wake word     : {args.wake_word}  (slug: {slug})")
    print(f"  Version       : {version}")
    print(f"  Customer      : {args.customer or '-'}")
    print(f"  License id    : {args.license_id or '-'}")
    print(f"  Model tag     : {model_tag or '-'}")
    print(line)
    print("  Quality")
    print(f"    Recall (stage1)   : {fmt(tm.get('stage1_recall'), '{:.3f}')}"
          + (f"   (stage2 {fmt(tm.get('stage2_recall'), '{:.3f}')})" if stage2_on else ""))
    print(f"    FA / hour         : {fmt(em.get('fa_per_hr'), '{:.3f}')}"
          f"   FRR: {fmt(em.get('frr'), '{:.1f}%')}")
    print(f"    ECE (calibration) : {fmt(em.get('ece'), '{:.4f}')}"
          f"   AUROC: {fmt(em.get('auroc'), '{:.4f}')}")
    op = em.get("op_M")
    if op is not None:
        print(f"    Operating point   : M={op}  s1_thr={fmt(em.get('stage1_thr'))}"
              + (f"  s2_thr={fmt(em.get('stage2_thr'))}" if stage2_on else ""))
    print(line)
    print("  Model size")
    print(f"    Stage-1 : {fmt(tm.get('stage1_size_kb'), '{:.1f} KB')}"
          + (f"    Stage-2 : {fmt(tm.get('stage2_size_kb'), '{:.1f} KB')}" if stage2_on else "")
          + f"    Total : {fmt(em.get('total_size_kb'), '{:.1f} KB')}")
    print(line)
    print("  Licensing / integrity")
    print(f"    Signed manifest : {'yes' if signed else 'no'}")
    print(f"    Files hashed    : {len(manifest.get('files', {})) or 'n/a'} (sha256 each)")
    print(line)
    print("  DELIVERABLE")
    if zip_path:
        print(f"    zip    : {zip_path}")
    else:
        print("    zip    : NOT FOUND — check train.py bundling output above "
              f"(looked under {os.path.join(HERE, args.dist_root)}).")
    if bundle_dir:
        print(f"    folder : {bundle_dir}")
    print("=" * 70)

    if not zip_path:
        sys.exit(2)


if __name__ == "__main__":
    main()
